field: e691301b-7484-40be-a3d4-c3bc590de959 # Content Builder
fieldLayouts:
  7d15571b-c1d6-4a10-ae40-f21cdc67cf8d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e7b63d80-91cc-438a-b670-59cbb778ca14 # Heading
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a238ef66-d312-4549-98e8-c47370083a80
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 77420046-8b89-462e-97a5-c10d770f6003
        userCondition: null
fields:
  e7b63d80-91cc-438a-b670-59cbb778ca14: # Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: 'The full heading of the section header'
    name: Heading
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: Title.json
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: sectionHeader
name: 'Section Header'
sortOrder: 1
